version: '2'
services:

  order:
    build: .
    container_name: "order"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - default
    depends_on:
      - db
    links:
      - pinpoint:pinpointhost


  db:
    image: mysql:5.6
    container_name: "orderdb"
    environment:
       MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3306:3306"
    networks:
      - default

  pinpoint:
    image: zuorn/pinpoint-server
    container_name: "pinpoint-server"
    ports:
      - "28080:28080"
    networks:
      - default

