version: '2'
services:
  pinpoint-server:
    image: zuorn/pinpoint-server
    container_name: pinpoint-server
    ports:
      - "19001:22"
      - "28080:28080"
    restart: always

    networks:
      - defaults

  order:
    image: bolingcavalry/centos67-pinpoint163-agent:0.0.1
    container_name: order
    command: sh bin/startup.sh
    ports:
      - "8080:8080"
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:5.6
    restart: always
    container_name: "mysql_5_7"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
     - 3306:3306
    links:
      - order
    networks:
      - default
